name: Generate executables and post them to release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        rust:
          - stable
        target:
          - x86_64-unknown-freebsd
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - run: cargo build --release

      - name: Upload executable to releases
        uses: Asthowen/UploadReleaseAsset@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_tag: ${{ steps.rtpm_version.outputs.APP_VERSION }}
          asset_path: ./target/release/rtpm
          asset_name: rtpm-${{ steps.rtpm_version.outputs.APP_VERSION }}-x86_64-unknown-freebsd
          asset_content_type: application/octet-stream
